-- Case party table updates
ALTER TABLE case_party
  ALTER COLUMN reference_number TYPE VARCHAR(5);


-- Case table updates
ALTER TABLE pt_case
  ADD COLUMN hearing_requested YES_NO;


-- Property inspection table updates
CREATE TABLE property_inspection (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description VARCHAR(100),
  inspection_date TIMESTAMP ,
  agree_to_decision_without_inspection YES_NO NOT NULL,
  no_decision_without_inspection_reason VARCHAR (500) ,
  created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_modified_by VARCHAR (100),
  pt_case_id BIGINT NOT NULL
);

ALTER TABLE property_inspection
  ADD FOREIGN KEY (pt_case_id)
  REFERENCES pt_case (id);

CREATE INDEX property_inspection_pt_case_id_idx
  ON property_inspection (pt_case_id);


-- Notice of rent change table updates
ALTER TABLE notice_of_rent_change
  ADD COLUMN received_landlord_notice_proposing_new_rent YES_NO,
  ADD COLUMN no_upload_of_notice_proposing_new_rent_reason VARCHAR(500),
  ADD COLUMN rent_increase_to_cause_hardship YES_NO,
  ADD COLUMN notice_legally_valid YES_NO,
  ADD COLUMN notice_not_legally_valid_details VARCHAR(500);

ALTER TABLE notice_of_rent_change
  ALTER COLUMN received_landlord_notice_proposing_new_rent SET NOT NULL,
  ALTER COLUMN rent_increase_to_cause_hardship SET NOT NULL,
  ALTER COLUMN notice_legally_valid SET NOT NULL;


-- Document table updates
CREATE TYPE DOCUMENT_TYPE AS ENUM (
  'HARDSHIP_EVIDENCE',
  'TENANCY_AGREEMENT',
  'NEW_RENT_INCREASE_NOTICE',
  'NOTICE_NOT_LEGALLY_VALID_EVIDENCE',
  'FLOOR_PLAN',
  'OUTSIDE_PROPERTY',
  'PROPERTY_ROOMS',
  'REPAIRS_EVIDENCE'
);

ALTER TABLE document
  ADD COLUMN document_type DOCUMENT_TYPE;

ALTER TABLE document
  ALTER COLUMN document_type SET NOT NULL;

ALTER TABLE document
  ALTER COLUMN size TYPE BIGINT,
  ALTER COLUMN category_id TYPE VARCHAR(50);
