ALTER TABLE case_party
  ALTER COLUMN reference_number TYPE VARCHAR(5);

ALTER TABLE pt_case
  ADD COLUMN hearing_requested YES_NO; -- todo not null in ddl but cannot be

CREATE TABLE property_inspection (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description VARCHAR(100),
  inspection_date TIMESTAMP ,
  agree_to_decision_without_inspection YES_NO, -- not null
  no_decision_without_inspection_reason VARCHAR (500) ,
  created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_modified_by VARCHAR (100),
  --   case_hearing_id INTEGER, -- no FK?
  pt_case_id BIGINT NOT NULL
);

ALTER TABLE property_inspection
  ADD FOREIGN KEY (pt_case_id)
  REFERENCES pt_case (id);

CREATE INDEX property_inspection_pt_case_id_idx
  ON property_inspection (pt_case_id);

-- todo
-- ALTER TABLE property_inspection
--   ADD FOREIGN KEY (case_hearing_id)
--   ON case_hearing (id);
-- todo
-- CREATE INDEX property_inspection_case_hearing_id_idx
--   ON property_inspection (case_hearing_id);
